UDL_TRACKS.push({
  id: "capcut", num: 9, name: "CapCut", abbr: "Cc", color: "#F4F4F7", group: "video",
  focus: "Shorts · Reels · TikTok · Fast Edits",
  intro: "Edit viral short-form video on your phone. Captions, beats, effects and templates that grow channels.",
  modules: [
    { title: "Interface & Core Tools", tag: "Foundations", lessons: [
      L("Projects & The Timeline",
        "CapCut is built for **vertical short-form** video. Your phone is a full editing studio.",
        ["**New project** → pick clips in order", "Preview (top), timeline (middle), toolbar (bottom)", "Pinch the timeline to zoom", "White playhead line = current frame"],
        [["Tap New project", "Start editing"], ["Pinch timeline", "Zoom in/out"], ["Tap clip", "Select clip"], ["Desktop: Space", "Play / pause"], ["Desktop: Ctrl + Z", "Undo"]],
        "Set **aspect ratio 9:16** (Ratio button) first. Changing it later breaks framing.",
        "Start a Reel project.",
        ["Open CapCut → New project", "Select 5 clips from your gallery", "Tap **Ratio** → 9:16", "Play through once", "Pinch to zoom the timeline"],
        ["How long is your raw timeline?", "Phone or desktop CapCut?"]),
      L("Split, Trim & Delete",
        "Short-form lives on **tight cuts**. Remove every dead second.",
        ["Drag clip edges to trim", "Move playhead → **Split**", "Select → **Delete**", "Long-press to reorder clips"],
        [["Split button", "Cut at playhead"], ["Long-press clip", "Reorder"], ["Desktop: Ctrl + B", "Split"], ["Desktop: Delete", "Delete clip"]],
        "Cut the first second of almost every clip. Viewers swipe if nothing happens **instantly**.",
        "Tighten your clips.",
        ["Trim each clip to its best 2-3 seconds", "Split and delete any shaky parts", "Reorder for the strongest opening", "Total under 20 seconds"],
        ["Final length?", "Which clip opens the video and why?"]),
      L("Canvas, Scale & Background",
        "Fill the 9:16 frame. Black bars look amateur.",
        ["Pinch the preview to scale clips", "Canvas → Blur background for horizontal clips", "Canvas color for clean looks", "Keep faces in the upper third"],
        [["Pinch preview", "Scale clip"], ["Canvas → Blur", "Blurred background fill"]],
        "Horizontal clip? Scale to fill and reframe, or use **Canvas → Blur** for a clean fill.",
        "Fix framing.",
        ["Import one horizontal clip", "Try Canvas → Blur", "Try scaling to fill instead", "Pick the better one"],
        ["Which looked better?"])
    ]},
    { title: "Text, Audio & Captions", tag: "Building Blocks", lessons: [
      L("Text & Styles",
        "On-screen text hooks muted viewers. Big, bold, high contrast.",
        ["Text → Add text", "Styles: stroke or background box", "Animations: In / Out", "Keep within safe zone (not behind buttons)"],
        [["Text → Add text", "New text layer"], ["Drag handles", "Resize/rotate text"]],
        "Avoid the **bottom 20% and right edge**: app buttons and captions cover them.",
        "Add a hook text.",
        ["Add text: **3 apps that pay you in crypto**", "Bold font, white with black stroke", "Animation In: Pop", "Keep it on for 2 seconds"],
        ["Screenshot"]),
      L("Auto Captions",
        "Captions increase watch time. CapCut generates them automatically.",
        ["Text → Auto captions", "Choose language", "Edit mistakes", "Apply a caption style to all"],
        [["Text → Auto captions", "Generate"], ["Batch edit", "Fix multiple lines"]],
        "Highlight **key words** in a color. That's the viral caption style.",
        "Caption a talking clip.",
        ["Record 20 s of you talking", "Auto captions", "Fix errors", "Style with highlight words"],
        ["How many errors did you fix?"]),
      L("Music, Voiceover & Sound",
        "Sound is half the video. Trending audio boosts reach.",
        ["Audio → Sounds or extract from a video", "Voiceover: record directly", "Volume: voice 100, music 10-20", "Beats: auto-mark beat points"],
        [["Audio → Voiceover", "Record"], ["Audio → Beats", "Mark beats"]],
        "Use **Voice enhance / noise reduction** on phone recordings.",
        "Add music and voiceover.",
        ["Add a music track", "Record a 10 s voiceover", "Balance volumes", "Enable beat marks"],
        ["Volume levels used?"])
    ]},
    { title: "Effects, Speed & Keyframes", tag: "Core Skills", lessons: [
      L("Transitions & Effects",
        "Use transitions on beats, not everywhere.",
        ["Tap the square between clips → transitions", "Effects: shake, flash, glitch on beats", "Filters for mood", "Adjust for manual color"],
        [["Tap transition icon", "Add transition"], ["Effects → Video effects", "Add effect"]],
        "One **consistent** transition style looks pro; ten different ones look amateur.",
        "Add effects on beats.",
        ["Add 2 transitions at beat points", "Flash effect on the drop", "A filter at 50%"],
        ["Which effect fit best?"]),
      L("Speed & Speed Ramps",
        "Speed ramps add energy: fast-slow-fast.",
        ["Speed → Normal: constant speed", "Speed → Curve: ramps (Montage, Hero)", "Smooth slow-mo option", "Match ramps to beats"],
        [["Speed → Curve", "Speed ramp"]],
        "Ramp **into slow-mo** right on the beat drop.",
        "Make a speed ramp.",
        ["Choose an action clip", "Apply Curve → Hero", "Align slow part to the beat"],
        ["Screenshot"]),
      L("Keyframes & Zoom",
        "Keyframes animate position, scale and opacity over time.",
        ["Tap the diamond icon to add a keyframe", "Move playhead, change scale: new keyframe", "Punch-in zoom on key words", "Smooth with graphs"],
        [["◇ button", "Add keyframe"]],
        "A slow **zoom-in over 3 seconds** keeps talking clips alive.",
        "Animate a zoom.",
        ["Keyframe at start (100%)", "Keyframe at 3 s (115%)", "Play"],
        ["Did it feel smooth?"])
    ]},
    { title: "Reel Ad Project", tag: "Project", lessons: [
      L("Hook, Body, CTA",
        "15-30 second ad: hook (0-3 s), value, CTA.",
        ["Hook: question or bold claim", "Body: product in action", "Offer/price", "CTA: DM, link in bio"],
        [["Text → Add text", "Hook text"]],
        "Show the **product in the first second**.",
        "Ad for **Mama Ngozi's Kitchen**.",
        ["Write hook", "Plan 5 shots", "Record or gather clips"],
        ["Your hook"]),
      L("Edit the Ad",
        "Beats, text, captions, transitions.",
        ["Cut to music beats", "Text overlays for offer", "Captions for voiceover", "Logo end card"],
        [["Audio → Beats", "Beat markers"]],
        "Put the **price and CTA on screen for 2+ seconds** so viewers can read.",
        "Edit the restaurant ad.",
        ["Cut to beats", "Add offer text", "Logo end card"],
        ["Length?"]),
      L("Export & Post",
        "Export settings and posting best practice.",
        ["Export 1080p, 30fps (or 60 for motion)", "Cover image selection", "Caption + hashtags", "Post at peak times"],
        [["Export button (top right)", "Export"], ["Desktop: Ctrl + E", "Export"]],
        "Pick a **cover frame** with big text: it shows in your grid.",
        "Export and post.",
        ["Export 1080p", "Choose cover", "Write caption + 5 hashtags"],
        ["Your caption"])
    ]},
    { title: "YouTube Shorts Project", tag: "Project", lessons: [
      L("Talking-Head Short",
        "Fast-cut talking-head Shorts are the easiest to grow with.",
        ["Record in good light", "Cut every pause", "Punch-in zooms", "Captions with highlights"],
        [["Split", "Cut"], ["◇", "Keyframe"]],
        "Record near a **window**; natural light beats cheap ring lights.",
        "Chainsense crypto tip Short.",
        ["Record 45 s tip", "Cut pauses", "Zooms and captions"],
        ["Final length?"]),
      L("B-Roll & Overlays",
        "Overlays show what you're talking about.",
        ["Overlay → Add overlay", "Screenshots of charts", "Green screen / chroma key", "Remove background (cutout)"],
        [["Overlay → Add overlay", "Add layer"], ["Remove BG", "Cutout person"]],
        "Use **Remove background** to put yourself in front of a chart.",
        "Add chart overlays.",
        ["Add a chart screenshot overlay", "Cutout yourself in front", "Animate in"],
        ["Screenshot"]),
      L("Series & Templates",
        "Consistency builds audiences. Make a reusable format.",
        ["Same intro text style", "Same caption style", "Save as template", "Batch-produce 3 at once"],
        [["Duplicate project", "Reuse format"]],
        "Batch record **5 Shorts in one session**, edit them from one duplicated project.",
        "Create a Shorts template.",
        ["Finalize a format", "Duplicate the project", "Swap clips for a second Short"],
        ["How long did the 2nd one take?"])
    ]},
    { title: "Animated Flier & Poster", tag: "Project", lessons: [
      L("Flier to Motion",
        "Turn a static flier into an animated status video.",
        ["Import flier layers as images", "Stagger text animations", "Add subtle zoom", "Music"],
        [["Overlay", "Layer images"]],
        "Export PNG layers from your design app for **clean separate animations**.",
        "Animate the Youth Fest flier.",
        ["Import background, headline, details as layers", "Animate each in sequence", "Music"],
        ["Length?"]),
      L("Poster Reveal",
        "Cinematic reveal: blur to sharp, light sweep, title slam.",
        ["Blur effect keyframed", "Light leak overlay", "Title Pop animation", "Impact SFX"],
        [["Effects", "Blur / light leak"]],
        "Sync the **title slam** with a bass hit for impact.",
        "Poster reveal video.",
        ["Blur to sharp", "Light sweep", "Title slam on beat"],
        ["Screenshot"]),
      L("Templates & Trends",
        "CapCut templates speed you up. Customize to avoid looking generic.",
        ["Browse templates", "Replace media", "Change text and colors", "Credit and adapt trends"],
        [["Templates tab", "Browse"]],
        "Use templates for **speed**, not identity. Always add your brand touch.",
        "Customize a template.",
        ["Pick a trending template", "Replace clips and text", "Add your logo"],
        ["Which template?"])
    ]},
    { title: "Pro Workflow & Growth", tag: "Pro", lessons: [
      L("CapCut Desktop",
        "Move to desktop CapCut for longer, heavier projects.",
        ["Same tools, bigger timeline", "Keyboard shortcuts", "Multi-track editing", "Cloud sync between phone and PC"],
        [["Ctrl + B", "Split"], ["Space", "Play"], ["Ctrl + E", "Export"], ["Ctrl + Z", "Undo"]],
        "Start on phone, **finish on desktop** with cloud space.",
        "Open a project on desktop (optional).",
        ["Install CapCut desktop", "Sync a project via cloud", "Edit with shortcuts"],
        ["Phone or desktop: which is faster for you?"]),
      L("Analytics & Iteration",
        "Improve with data: retention, watch time, shares.",
        ["Check average watch time", "Find the drop-off second", "Test 2 hooks", "Double down on winners"],
        [["Duplicate project", "Make hook variants"]],
        "Post the **same video with 2 different hooks** a week apart. Learn what works.",
        "Make hook variants.",
        ["Duplicate a finished video", "Change only the hook", "Export both"],
        ["Your two hooks"]),
      L("Portfolio & Clients",
        "Sell short-form editing to brands and creators.",
        ["Reel of your 5 best edits", "Before/after clips", "Package prices: 4 / 8 / 12 videos", "DM local businesses"],
        [["Export", "Final render"]],
        "Offer local businesses **4 Reels/month** packages: steady income.",
        "Build your editing reel.",
        ["Compile best 5 edits", "Add your contact", "Export and post"],
        ["Your package price idea?"])
    ]}
  ]
});
