UDL_TRACKS.push({
  id: "coreldraw", num: 1, name: "CorelDRAW", abbr: "Cdr", color: "#3DDC97", group: "design",
  focus: "Logos · Fliers · Posters · Vector Design",
  intro: "The Nigerian print-shop standard. Master vectors, then ship a logo, a flier and a poster a client would pay for.",
  modules: [
    { title: "Interface & Core Tools", tag: "Foundations", lessons: [
      L("The Workspace",
        "CorelDRAW is **vector** software. Shapes are math, not pixels, so they scale to billboard size with zero blur. That's why logos live here.",
        ["**Toolbox** (left): your drawing tools", "**Property Bar** (top): settings for whatever is selected", "**Drawing Page** (center): only what sits on the page prints", "**Color Palette** (right) and **Dockers** (right panel) for color and advanced settings"],
        [["Ctrl + N", "New document"], ["F6", "Rectangle tool"], ["F7", "Ellipse tool"], ["Spacebar", "Toggle back to Pick tool"], ["Shift + F4", "Zoom to page"], ["Ctrl + S", "Save"]],
        "**Left-click** a palette swatch = fill. **Right-click** = outline. Pros never open a menu to change color.",
        "Every logo starts as simple shapes. The Olympic rings are just ellipses.",
        ["`Ctrl + N` → A4 page → OK", "`F6` → drag a rectangle", "`F7` → hold **Ctrl** and drag a perfect circle", "Circle selected → left-click red, right-click black", "`Spacebar` → drag the circle to overlap the rectangle", "`Ctrl + S` → save as **Lab01_Shapes.cdr**"],
        ["Done, or where you got stuck?", "What does holding Ctrl do to the ellipse?", "Which CorelDRAW version are you on?"],
        "If the shape won't draw, make sure the tool is active (it's highlighted in the toolbox) and you're dragging on the page."),
      L("Select, Move & Transform",
        "The **Pick tool** does 90% of your work: select, move, scale, rotate. Click once for scale handles, click again for rotate/skew handles.",
        ["Drag corner handles to scale; hold **Shift** to scale from the center", "Click a selected object again → rotation arrows appear", "Drag an empty area to marquee-select many objects", "**Shift + click** adds or removes objects from a selection"],
        [["Spacebar", "Pick tool"], ["Ctrl + D", "Duplicate"], ["+ (numpad)", "Duplicate in place"], ["Arrow keys", "Nudge selection"], ["Ctrl + Z", "Undo"]],
        "While dragging an object, **right-click before releasing** to drop a copy. Fastest duplicate in the game.",
        "A fashion brand wants a pattern of repeated diamonds for a label.",
        ["Draw a square with `F6` + **Ctrl**", "Click it twice → rotate 45° with **Ctrl** held (snaps in 15° steps)", "Drag it right and right-click before release to drop a copy", "`Ctrl + R` (repeat) 4 times to make a row of 6", "Marquee-select the row and color it navy"],
        ["How many diamonds in your row?", "What does Ctrl do while rotating?"]),
      L("Zoom, Pan & Organize",
        "Speed = navigation. The **Objects docker** is your layer list; it keeps big designs sane.",
        ["**Objects docker**: Window → Dockers → Objects", "Name your objects so you can find them later", "Lock layers you've finished so you don't bump them", "Use **Wireframe** view to see hidden shapes"],
        [["F4", "Zoom to all objects"], ["Shift + F4", "Zoom to page"], ["H", "Pan tool"], ["Z", "Zoom tool"], ["Scroll wheel", "Zoom in/out at cursor"]],
        "Hold the **middle mouse button** and drag to pan without switching tools.",
        "A print shop sends you a messy file with 40 unnamed objects.",
        ["Open Lab01_Shapes.cdr", "Open the Objects docker", "Rename your circle **Sun** and rectangle **Base**", "Lock the Base", "Try moving it: confirm it won't budge", "`F4` then `Shift + F4` and note the difference"],
        ["What's the difference between F4 and Shift + F4?", "Where did you find the lock icon?"])
    ]},
    { title: "Shapes, Color & Text", tag: "Building Blocks", lessons: [
      L("Shaping: Weld, Trim, Intersect",
        "Pro logos are built by combining simple shapes. **Shaping** merges or cuts them into one custom form.",
        ["**Weld**: merge shapes into one outline", "**Trim**: cut the top shape out of the bottom one", "**Intersect**: keep only the overlap", "Buttons appear on the Property Bar when 2+ shapes are selected"],
        [["Ctrl + L", "Combine"], ["Ctrl + K", "Break apart"], ["Ctrl + Q", "Convert to curves"], ["F10", "Shape tool (edit nodes)"]],
        "Select the **cutter first**, then Shift-click the target. The last selected object is what gets trimmed.",
        "A delivery startup wants a cloud-shaped icon.",
        ["Draw 3 overlapping circles and 1 rectangle along their base", "Select all → **Weld** → one cloud", "Draw a small circle over the cloud → **Trim** to punch a hole", "Delete the cutter circle", "Fill the cloud sky-blue, no outline"],
        ["Screenshot or describe your cloud", "What happened to the cutter after Trim?"]),
      L("Color Like a Pro",
        "Color sells the design. Use **CMYK** for print, **RGB** for screens. Fliers and posters are CMYK.",
        ["**Uniform fill**: one solid color", "**Fountain fill**: gradients", "Pick a palette of 2 main colors + 1 accent", "Use the **Eyedropper** to copy exact colors between objects"],
        [["Shift + F11", "Uniform fill dialog"], ["F11", "Fountain fill"], ["F12", "Outline pen"], ["I", "Eyedropper (Attributes)"]],
        "Rich black for print: **C60 M40 Y40 K100**. Plain K100 prints washed out on big areas.",
        "A restaurant wants a warm, appetizing palette.",
        ["Draw 3 squares in a row", "Fill with CMYK values: **0 60 100 0**, **0 20 90 0**, **60 40 40 100**", "Add a 4th square with a fountain fill between the first two", "Give all squares a 2pt white outline with `F12`"],
        ["What values did you use for the gradient?", "Why CMYK for a flier?"]),
      L("Text & Typography",
        "**Artistic text** is for headlines and logos. **Paragraph text** is for body copy in a frame.",
        ["Click with the Text tool = artistic text", "Drag a box with the Text tool = paragraph text", "Pair max **2 fonts**: one bold display, one clean body", "Convert logo text to curves before sending to print"],
        [["F8", "Text tool"], ["Ctrl + T", "Text properties"], ["Ctrl + Q", "Convert to curves"], ["Ctrl + Shift + T", "Edit text"]],
        "Tighten headline **kerning** with the Shape tool: drag the arrow under the text left.",
        "A church youth group needs a bold event title.",
        ["`F8` → click and type **YOUTH FEST 2026**", "Set a heavy sans-serif, 72pt", "Add paragraph text below: date, venue, time", "Use a lighter font for the details", "Duplicate the title → `Ctrl + Q` on the copy"],
        ["Which 2 fonts did you pair?", "What changes after Ctrl + Q?"])
    ]},
    { title: "Curves, Effects & Layout", tag: "Core Skills", lessons: [
      L("Bezier & Pen Curves",
        "Custom shapes come from **nodes** and **curves**. This is how pros draw icons from scratch.",
        ["**Bezier / Pen tool**: click = straight point, drag = curve", "**Shape tool (F10)** edits nodes after drawing", "Fewer nodes = smoother curves", "Close a shape by clicking the first node"],
        [["F10", "Shape tool"], ["F5", "Freehand tool"], ["Double-click path", "Add node (Shape tool)"], ["Delete", "Remove selected node"]],
        "Import a sketch, lock it, and trace on top. That's the real pro workflow.",
        "Draw a leaf icon for an agro brand.",
        ["Pen tool → click-drag 3 points to form a leaf outline, close it", "`F10` → adjust nodes for smooth curves", "Draw a center vein with a single curve", "Fill the leaf green, vein white"],
        ["How many nodes did your leaf end up with?", "Which tool fixed the curves?"]),
      L("PowerClip & Transparency",
        "**PowerClip** puts an image inside a shape. **Transparency** creates depth and overlays.",
        ["Object → PowerClip → **Place Inside Frame**", "Ctrl-click the frame to edit the contents", "Transparency tool: drag across an object for a fade", "Use transparency for overlays on busy photos"],
        [["Ctrl + I", "Import image"], ["Ctrl + click", "Edit PowerClip contents"], ["Alt + Enter", "Object properties"]],
        "Import photos at **300 DPI** for print. Anything lower looks soft on a flier.",
        "Put a food photo inside a circle for a menu design.",
        ["`Ctrl + I` → import any photo", "Draw a circle", "Photo selected → Object → PowerClip → Place Inside Frame → click the circle", "Add a black rectangle over half the page → apply 40% transparency", "Type white text on the dark area"],
        ["Did the photo fit? How did you reposition it?", "What transparency value looked best?"]),
      L("Align, Distribute & Grids",
        "Clean alignment is what separates amateur from pro. Everything should line up with something.",
        ["**Align & Distribute** docker: Ctrl + Shift + A", "Use **guidelines**: drag from the rulers", "Keep a consistent margin (e.g. 10 mm) on every side", "Group finished parts with Ctrl + G"],
        [["P", "Center to page"], ["C / E", "Align centers vertical / horizontal"], ["L / R / T / B", "Align left / right / top / bottom"], ["Ctrl + G", "Group"], ["Ctrl + U", "Ungroup"]],
        "The **last selected** object is the anchor others align to. Select the anchor last.",
        "Lay out a business card with perfect alignment.",
        ["New page **90 × 55 mm**", "Add guidelines 5 mm from every edge", "Place a logo shape, name, title, phone, email", "Align text left to the same guideline", "Group everything → press `P`"],
        ["What margin did you use?", "Which shortcut centered your design?"])
    ]},
    { title: "Logo Project", tag: "Project", lessons: [
      L("Brief & Sketch",
        "Logos start on paper, not the screen. A **brief** defines the client, the audience and the feeling.",
        ["Ask: who is it for, what do they sell, what feeling?", "Sketch **10 thumbnails** fast; no detail", "Pick the 2 strongest to digitize", "Great logos work in **one color** and tiny sizes"],
        [["Ctrl + I", "Import sketch"], ["Object → Lock", "Lock the sketch"], ["F10", "Shape tool"]],
        "Test by squinting: if the logo still reads, it's strong.",
        "Client: **Urban Farms**, a Benin City agro business. Feeling: fresh, trusted, modern.",
        ["Write a 3-line brief: audience, values, colors", "Sketch 10 icon ideas on paper (leaf, sun, field, U-shape...)", "Photograph the best 2", "Import them into CorelDRAW and lock them"],
        ["Share your 3-line brief", "Describe your top 2 concepts"]),
      L("Build the Mark",
        "Digitize the icon with shapes and shaping tools. Precision and balance matter more than detail.",
        ["Trace over your sketch with basic shapes first", "Weld and trim to form the final mark", "Use a **grid of circles** for perfect curves", "Keep line weights consistent"],
        [["Ctrl + L", "Combine"], ["Ctrl + K", "Break apart"], ["F12", "Outline pen"], ["Ctrl + Shift + Q", "Convert outline to object"]],
        "Always **Convert outline to object** before scaling a logo, or strokes won't scale evenly.",
        "Build the Urban Farms icon.",
        ["Trace your chosen sketch with shapes and the Pen tool", "Weld / trim into one clean icon", "Convert any outlines to objects", "Test it at 1 cm wide: does it still read?"],
        ["Screenshot your mark", "How many nodes / shapes is it built from?"]),
      L("Wordmark & Lockups",
        "Pair the icon with type. A **lockup** is the fixed arrangement of icon + name.",
        ["Make a **horizontal** and a **stacked** lockup", "Match the font's weight to the icon's weight", "Create **full color, black, and white** versions", "Keep clear space around the logo (e.g. height of one letter)"],
        [["F8", "Text tool"], ["Ctrl + Q", "Text to curves"], ["Ctrl + G", "Group"], ["Ctrl + Shift + A", "Align & Distribute"]],
        "Kern the wordmark by hand. Default spacing between letters like **A, V, T** always looks off.",
        "Finish the Urban Farms logo system.",
        ["Add the wordmark **URBAN FARMS** next to the icon", "Kern the letters, convert to curves", "Make a stacked version", "Duplicate both: full color, all black, all white on a dark box", "Arrange all versions on one page"],
        ["How many versions did you make?", "Which lockup do you prefer and why?"])
    ]},
    { title: "Flier Project", tag: "Project", lessons: [
      L("Flier Setup & Hierarchy",
        "A flier must be understood in **3 seconds**. Hierarchy decides what the eye sees first.",
        ["Size: **A5** (148 × 210 mm) is the flier standard", "Add **3 mm bleed** so edges print clean", "Order: Headline → Visual → Key details → Call to action", "Keep text 5 mm inside the trim line (safe zone)"],
        [["Ctrl + J", "Options (bleed & page)"], ["Ctrl + N", "New document"], ["Double-click ruler", "Guideline setup"]],
        "Set bleed in the document setup and turn on **Show bleed**. Background images must extend into it.",
        "Flier for **Mama Ngozi's Kitchen** grand opening: 20% off, Saturday, Ring Road, Benin City.",
        ["New A5 CMYK document with 3 mm bleed", "Add safe-zone guidelines 5 mm inside", "Block out zones with grey rectangles: headline, image, details, CTA", "Write the actual text for each zone"],
        ["What's your headline?", "Describe your layout zones"]),
      L("Build the Flier",
        "Turn the wireframe into a design: photo, color, type, contrast.",
        ["Headline: huge, bold, high contrast", "Use one hero image via PowerClip", "Put the **offer** (20% OFF) in a shape badge", "Contact + address small and clean at the bottom"],
        [["Ctrl + I", "Import"], ["Shift + PgUp", "Bring to front"], ["Shift + PgDn", "Send to back"], ["Ctrl + PgUp", "Forward one"]],
        "Squint test again. If the offer and headline don't pop, increase contrast, not size.",
        "Design the Mama Ngozi's Kitchen flier.",
        ["Replace grey blocks with a food photo, headline and details", "Make a **20% OFF** starburst badge (Star tool)", "Apply your 3-color palette", "Add logo, phone number and address at the bottom"],
        ["Screenshot your flier", "What's the first thing the eye sees?"]),
      L("Polish & Proof",
        "Proofing catches the mistakes that cost reprints: typos, low-res images, missing bleed.",
        ["Spell-check every word, especially phone numbers", "Check images are 300 DPI at printed size", "Convert fonts to curves for the print copy", "Use **Pre-flight** (in PDF export) to catch issues"],
        [["Ctrl + Q", "Convert to curves"], ["Ctrl + E", "Export"], ["Ctrl + Shift + S", "Save as"]],
        "Save a **master .cdr with live text** and a separate curves copy for print. Never lose your editable file.",
        "Get the flier print-ready.",
        ["Read every line out loud", "Save as **Flier_MASTER.cdr**", "Save a copy, select all text → `Ctrl + Q` → save as **Flier_PRINT.cdr**", "Export a PDF and review it at 100%"],
        ["Did you find any errors?", "Paste your final file names"])
    ]},
    { title: "Poster Project", tag: "Project", lessons: [
      L("Poster Scale & Impact",
        "Posters are read from **3 meters away**. One big idea, one strong visual, minimal text.",
        ["Common sizes: **A2** (420 × 594 mm), **A3** for small runs", "Headline should be readable across a room", "Use a strong focal point: face, product, or bold graphic", "Limit to 3 text levels"],
        [["Ctrl + J", "Page setup"], ["F4", "Zoom to all"], ["Ctrl + D", "Duplicate"]],
        "Zoom out until the poster is thumbnail size. If it's still readable, it'll work on a wall.",
        "Event poster: **Edo/Delta Youth Summit 2026**.",
        ["New A2 CMYK page, 3 mm bleed", "Write the headline, date, venue, 3 speakers, CTA", "Sketch 3 layout thumbnails in small boxes on the page", "Pick the strongest"],
        ["Which layout won?", "What's your focal point?"]),
      L("Build the Poster",
        "Combine everything: PowerClip photos, bold type, shapes, and transparency for depth.",
        ["Background: gradient or photo with a dark overlay", "Speakers in matching circle frames", "Headline with a **contour** or shadow for punch", "Keep strong alignment on a grid"],
        [["Ctrl + F9", "Contour docker"], ["Ctrl + G", "Group"], ["P", "Center to page"]],
        "Use **Effects → Drop Shadow** subtly. Heavy shadows look amateur.",
        "Design the Youth Summit poster.",
        ["Build background and overlay", "Place 3 speaker photos in circles with names below", "Style the headline", "Add date, venue and a registration QR placeholder"],
        ["Screenshot your poster", "What effect did you use on the headline?"]),
      L("Variations & Sizes",
        "Clients always ask for more sizes. Build a system that adapts.",
        ["Make a **square** (1080 × 1080 px) social version", "Make a **story** (1080 × 1920 px) version", "Re-arrange, don't just squash", "Keep the same palette, fonts and logo placement"],
        [["Ctrl + C / V", "Copy / paste between pages"], ["Page tab + right-click", "Insert page"], ["Ctrl + E", "Export"]],
        "Use **multiple pages** in one .cdr: one page per size. Easier to manage and export.",
        "Adapt the Youth Summit poster for Instagram.",
        ["Insert 2 new pages: 1080 × 1080 px and 1080 × 1920 px (RGB)", "Rebuild the layout for each shape", "Keep headline and date the most prominent"],
        ["What did you drop or move for the story version?"])
    ]},
    { title: "Export, Print & Portfolio", tag: "Pro", lessons: [
      L("Print-Ready PDF",
        "Printers want a **PDF with bleed and crop marks**. This is the pro handoff.",
        ["File → Export (Ctrl + E) → PDF, or **Publish to PDF**", "Preset: **PDF/X-4** or Prepress", "Include bleed and crop marks", "Check the pre-flight warnings tab"],
        [["Ctrl + E", "Export"], ["Ctrl + P", "Print"]],
        "Ask your printer for their **PDF preset**. Using theirs avoids 90% of problems.",
        "Send the flier to the print shop.",
        ["Open Flier_PRINT.cdr", "Export PDF with a Prepress / PDF/X preset", "Enable bleed + crop marks", "Open the PDF and check the marks are outside the design"],
        ["Any pre-flight warnings?", "What preset did you use?"]),
      L("Web & Social Exports",
        "Screens need **RGB PNG or JPG** at the right pixel size.",
        ["PNG for logos (transparent background)", "JPG for photo-heavy designs", "Export at exact pixel size (1080 × 1080 etc.)", "Keep file size under 1 MB for WhatsApp/IG"],
        [["Ctrl + E", "Export"], ["Ctrl + Shift + E", "Export for web/office (version dependent)"]],
        "Export logos at 2 sizes: **500 px** and **2000 px**, both transparent PNG.",
        "Deliver the logo pack.",
        ["Export all logo versions as transparent PNG", "Export the social poster versions as JPG", "Put them in a folder named **UrbanFarms_Logo_Pack**"],
        ["List your exported files"]),
      L("Portfolio & Pricing",
        "Your portfolio gets you clients. Show the problem, the process, and the result.",
        ["Show 3 projects: logo, flier, poster", "Include a sketch or before/after", "Mock up work in context (sign, phone, wall)", "Price by **value and time**, not by the hour alone"],
        [["Ctrl + E", "Export"], ["Ctrl + S", "Save"]],
        "Post one project per week on Instagram / Behance with a short caption about the brief.",
        "Build your first portfolio page.",
        ["New A4 landscape page", "Place the logo, flier and poster with a 1-line description each", "Add your name and contact", "Export as PDF and a JPG for social"],
        ["Share your portfolio caption", "What would you charge for the logo project?"])
    ]}
  ]
});
