UDL_TRACKS.push({
  id: "indesign", num: 4, name: "InDesign", abbr: "Id", color: "#FF4F8B", group: "design",
  focus: "Magazines · Brochures · Print Layout",
  intro: "The layout engine behind magazines and brochures. Master frames, styles and grids, then publish like a studio.",
  modules: [
    { title: "Interface & Core Tools", tag: "Foundations", lessons: [
      L("Documents, Pages & Bleed",
        "InDesign is for **multi-page layout**. Set margins, columns and bleed right at the start.",
        ["New Document: size, pages, facing pages, columns", "**Margins** (magenta) = safe zone", "**Bleed** (red) = 3 mm outside the trim", "Pages panel shows every page and spread"],
        [["Ctrl + N", "New document"], ["F12", "Pages panel"], ["W", "Toggle Preview / Normal mode"], ["Ctrl + 0", "Fit page"], ["Ctrl + Alt + 0", "Fit spread"]],
        "Press **W** often. Preview hides guides so you see the page like a reader.",
        "Set up a 4-page brochure.",
        ["`Ctrl + N` → A4, 4 pages, facing pages ON", "Margins 15 mm, 2 columns, 5 mm gutter", "Bleed 3 mm", "Open the Pages panel (F12) and view a spread", "Save as **Brochure.indd**"],
        ["How are the pages arranged in the Pages panel?", "InDesign version?"]),
      L("Frames: Text & Graphics",
        "Everything lives in a **frame**. Text frames hold words; graphic frames hold images.",
        ["Type tool (T): drag a text frame", "Rectangle Frame (F): placeholder for images", "Place (Ctrl + D) imports text or images", "Frames can link so text flows between them"],
        [["T", "Type tool"], ["F", "Rectangle frame"], ["Ctrl + D", "Place"], ["V / A", "Selection / Direct selection"]],
        "Right-click a text frame → **Fill with Placeholder Text** to design before copy arrives.",
        "Rough out the brochure cover.",
        ["Draw a big image frame (F) on page 1", "`Ctrl + D` → place a photo into it", "Draw a text frame for a title", "Fill a body frame with placeholder text"],
        ["Screenshot of page 1"]),
      L("Fitting Images",
        "Frame vs content: the frame crops, the content is the image inside. Fitting commands save hours.",
        ["Click the **content grabber** (donut) to move the image inside", "Fill Frame Proportionally = no gaps", "Fit Content Proportionally = see whole image", "Frame Fitting Options set auto-fit"],
        [["Ctrl + Alt + Shift + C", "Fill frame proportionally"], ["Ctrl + Alt + Shift + E", "Fit content proportionally"], ["Ctrl + Shift + E", "Center content"], ["Ctrl + Alt + C", "Fit frame to content"]],
        "Turn on **Auto-Fit** in Frame Fitting Options so images stay filled when you resize frames.",
        "Fix image crops.",
        ["Place 3 photos in different-shaped frames", "Fill proportionally", "Move each image inside its frame with the grabber", "Enable Auto-Fit on one and resize it"],
        ["Which shortcut did you use most?"])
    ]},
    { title: "Type, Styles & Color", tag: "Building Blocks", lessons: [
      L("Threading Text",
        "Long text flows through **threaded** frames. A red **+** means overset (hidden) text.",
        ["Click the out-port of a frame, then click/drag a new frame", "Shift-click to autoflow across pages", "Red + = overset text: fix before print", "View → Extras → Show Text Threads"],
        [["Ctrl + Alt + Y", "Show text threads"], ["Ctrl + Y", "Story editor"]],
        "Use **Smart Text Reflow** (Preferences → Type) to add pages automatically.",
        "Flow an article across 2 pages.",
        ["Place a long text document into page 2", "Click the red + and thread into page 3", "Check no overset remains"],
        ["Any overset text left?"]),
      L("Paragraph & Character Styles",
        "Styles = consistency + speed. Change one style, update the whole document.",
        ["**Paragraph styles**: headline, body, caption", "**Character styles**: bold words, links", "Base styles on each other (Body → Body Intro)", "Next Style: headline auto-followed by body"],
        [["F11", "Paragraph styles"], ["Shift + F11", "Character styles"], ["Ctrl + T", "Character panel"], ["Ctrl + Alt + T", "Paragraph panel"]],
        "Never format text manually in a long document. **Styles or nothing.**",
        "Style the article.",
        ["Create H1, Body, Caption paragraph styles", "Create a Bold Accent character style", "Apply them", "Change Body font size and watch everything update"],
        ["What changed when you edited the style?"]),
      L("Swatches & Color",
        "Define brand colors as **swatches** (CMYK for print). Apply to text, frames and strokes.",
        ["Swatches panel → New Color Swatch", "Use CMYK process colors for print", "Tints: lighter versions of a swatch", "Paper = white; [Registration] is not for design"],
        [["F5", "Swatches"], ["F6", "Color panel"], ["X", "Toggle fill/stroke"], ["J", "Apply none"]],
        "Never use **[Registration]** as black. Use [Black] or rich black for large areas.",
        "Add brand colors.",
        ["Create 3 CMYK swatches", "Make a 20% tint", "Apply to headline, a background box and a caption"],
        ["Your swatch values"])
    ]},
    { title: "Grids, Masters & Structure", tag: "Core Skills", lessons: [
      L("Parent (Master) Pages",
        "**Parent pages** hold repeating elements: page numbers, logos, footers.",
        ["Pages panel → A-Parent", "Add current page number marker", "Items on parent appear on every page", "Override on one page: Ctrl + Shift + click"],
        [["Ctrl + Shift + Alt + N", "Insert current page number"], ["Ctrl + Shift + click", "Override parent item"]],
        "Create a **B-Parent** for section openers with different layouts.",
        "Add page numbers and footer.",
        ["Double-click A-Parent", "Add a footer text frame with page number marker", "Add logo", "Check all pages"],
        ["Do numbers appear on all pages?"]),
      L("Grids & Alignment",
        "Grids make layouts look professional and consistent.",
        ["Layout → Margins and Columns", "Baseline grid aligns text across columns", "Smart Guides snap objects", "Align panel for precision"],
        [["Ctrl + Alt + '", "Show baseline grid"], ["Ctrl + ;", "Show guides"], ["Shift + F7", "Align panel"]],
        "Use **Layout → Create Guides** to build a 6-column grid in seconds.",
        "Build a magazine grid.",
        ["Create a 6-column grid with 12 rows", "Align images and text to it", "Turn on baseline grid for body text"],
        ["Screenshot"]),
      L("Tables & Text Wrap",
        "Tables for prices and schedules; text wrap flows text around images.",
        ["Table → Create Table", "Table styles keep them consistent", "Text Wrap panel: wrap around bounding box or shape", "Wrap offset gives breathing room"],
        [["Ctrl + Alt + Shift + T", "Create table"], ["Ctrl + Alt + W", "Text Wrap panel"]],
        "Use **Wrap around object shape** with a cutout PNG for magazine-style layouts.",
        "Add a price table and wrapped image.",
        ["Create a 3 × 5 table of products and prices", "Style it", "Place an image in body text with 5 mm wrap"],
        ["Screenshot"])
    ]},
    { title: "Brochure Project", tag: "Project", lessons: [
      L("Trifold Setup",
        "A trifold is one sheet folded twice. Panels are NOT equal: the fold-in panel is ~2 mm narrower.",
        ["A4 landscape, 2 pages (outside/inside)", "3 columns, adjust fold-in panel", "Know which panel is front cover", "Bleed 3 mm"],
        [["Ctrl + N", "New"], ["Ctrl + R", "Rulers"]],
        "Print a paper dummy, fold it and **write panel names** on it before designing.",
        "Client: **Urban Farms** product brochure.",
        ["A4 landscape, 2 pages", "Set up panels with guides", "Label panels: cover, back, inside flap, inside 1-3"],
        ["Your panel layout"]),
      L("Design the Brochure",
        "Cover grabs, inside informs, back converts.",
        ["Cover: logo + hero + promise", "Inside: products, benefits, table", "Back: contact, map, QR", "Consistent styles throughout"],
        [["F11", "Paragraph styles"], ["Ctrl + D", "Place"]],
        "Keep important text **away from folds** (5 mm buffer).",
        "Design the Urban Farms brochure.",
        ["Cover panel", "3 inside panels with products", "Back panel with contact"],
        ["Screenshot of both sides"]),
      L("Preflight & Export",
        "Preflight catches missing fonts, links and overset text.",
        ["Preflight panel (bottom bar green/red dot)", "Links panel: update missing images", "Export → PDF/X-1a or Press Quality with bleed", "Package for the printer"],
        [["Ctrl + E", "Export"], ["Ctrl + Shift + D", "Links panel"], ["Alt + Shift + Ctrl + P", "Package"]],
        "A **green preflight dot** before export means no missing fonts, links or overset text.",
        "Export the brochure.",
        ["Fix all preflight errors", "Export PDF with bleed + crop marks", "Package the file"],
        ["Preflight errors fixed?"])
    ]},
    { title: "Flier & Menu Project", tag: "Project", lessons: [
      L("Restaurant Menu Setup",
        "Menus are structured layouts: perfect for styles and tables.",
        ["A4 or DL size", "Sections: starters, mains, drinks", "Dot leaders between item and price (tab with leader)", "Clear hierarchy"],
        [["Ctrl + Shift + T", "Tabs panel"], ["F11", "Paragraph styles"]],
        "Use **right-aligned tabs with a dot leader** for pro price columns.",
        "Menu for **Mama Ngozi's Kitchen**.",
        ["A4 page", "Create styles: Section, Item, Description, Price", "Set right tab with dot leader"],
        ["Screenshot of a section"]),
      L("Design the Menu",
        "Photos, sections and prices, laid out for a hungry reader.",
        ["Hero food photo", "Section headers in accent color", "Items aligned perfectly", "Logo and contact"],
        [["Ctrl + D", "Place"], ["W", "Preview"]],
        "Put the **most profitable dishes** top-right; that's where eyes land first.",
        "Build the full menu.",
        ["Add all sections and items", "Add photos", "Logo and contact"],
        ["Screenshot"]),
      L("Event Flier",
        "Single-page fliers are fast in InDesign with styles.",
        ["Reuse styles", "Big headline", "Image frame + details", "Export for print and social"],
        [["Ctrl + E", "Export"]],
        "Export a **JPG** too (File → Export → JPEG) for WhatsApp sharing.",
        "Flier for the restaurant's Friday live band night.",
        ["A5 + bleed", "Headline, image, details, CTA", "Export PDF + JPG"],
        ["Screenshot"])
    ]},
    { title: "Magazine & Poster Project", tag: "Project", lessons: [
      L("Magazine Cover",
        "Covers sell: masthead, cover image, coverlines.",
        ["Masthead at top, huge", "Coverlines left third (visible on shelves)", "Cover photo behind masthead", "Barcode & issue info"],
        [["Ctrl + D", "Place"], ["Ctrl + Shift + ]", "Bring to front"]],
        "Let the subject's head **overlap the masthead** slightly: classic magazine look.",
        "Cover for **Chainsense Magazine** issue 1.",
        ["Masthead", "Cover image", "5 coverlines", "Issue number and date"],
        ["Screenshot"]),
      L("Feature Spread",
        "A 2-page article: big opener, pull quote, columns, captions.",
        ["Headline + deck (subtitle)", "Drop cap", "Pull quote", "Captions under images"],
        [["Ctrl + Alt + R", "Drop caps and nested styles"]],
        "Use **nested styles** to auto-bold the first line of each paragraph.",
        "Build a feature spread.",
        ["Headline and deck", "3-column body with drop cap", "Pull quote and image with caption"],
        ["Screenshot"]),
      L("Poster in InDesign",
        "Typographic posters with perfect grids.",
        ["A2 page", "Big typography on a grid", "Minimal images", "Event info block"],
        [["Ctrl + Shift + > / <", "Font size"]],
        "InDesign handles **huge type** better than most tools. Use it for type-led posters.",
        "Typographic poster for a book launch.",
        ["A2 with grid", "Title in massive type", "Info block", "Export PDF"],
        ["Screenshot"])
    ]},
    { title: "Export, Interactive & Portfolio", tag: "Pro", lessons: [
      L("Print Production",
        "Know your printer's specs: bleed, color, paper, finishing.",
        ["Ask for PDF preset", "CMYK only, 300 PPI images", "Total ink under ~300%", "Request a proof"],
        [["Shift + F6", "Separations Preview"], ["Ctrl + E", "Export"]],
        "Always request a **hard proof** for large print runs.",
        "Prepare a printer brief.",
        ["Write specs: size, paper, quantity, finish", "Export matching PDF"],
        ["Your brief"]),
      L("Interactive PDF & EPUB",
        "InDesign exports clickable PDFs and ebooks.",
        ["Hyperlinks panel", "Buttons for navigation", "Export → Interactive PDF", "EPUB for ebooks"],
        [["Ctrl + E", "Export"], ["Window → Interactive → Hyperlinks", "Hyperlinks panel"]],
        "Clickable **portfolio PDFs** impress clients more than static ones.",
        "Make a clickable PDF.",
        ["Add links to email and website", "Export Interactive PDF", "Test links"],
        ["Did links work?"]),
      L("Portfolio Book",
        "Build your portfolio as an InDesign document.",
        ["Cover + about page", "One spread per project", "Consistent styles", "Export interactive PDF"],
        [["F12", "Pages"]],
        "Keep your portfolio under **12 pages**. Quality over quantity.",
        "Build a portfolio book.",
        ["Cover, about, 3 project spreads, contact", "Export"],
        ["Share file name and page count"])
    ]}
  ]
});
