UDL_TRACKS.push({
  id: "photoshop", num: 2, name: "Photoshop", abbr: "Ps", color: "#4FB3FF", group: "design",
  focus: "Photo Editing · Compositing · Social Graphics",
  intro: "The king of pixels. Retouch photos, build composites, and create fliers and posters that stop the scroll.",
  modules: [
    { title: "Interface & Core Tools", tag: "Foundations", lessons: [
      L("Workspace & Documents",
        "Photoshop edits **raster** images: grids of pixels. Resolution matters: **300 PPI** for print, **72 PPI** for screens.",
        ["**Tools** (left), **Options bar** (top), **Panels** (right)", "Layers panel is your most important panel", "New doc: pick pixels for social, mm for print", "Color mode: RGB for screen, CMYK for final print"],
        [["Ctrl + N", "New document"], ["Ctrl + O", "Open"], ["Ctrl + 0", "Fit on screen"], ["Ctrl + 1", "100% view"], ["Spacebar (hold)", "Hand tool / pan"]],
        "Window → Workspace → **Essentials (Default)** resets messy panels instantly.",
        "Set up a canvas for an Instagram post.",
        ["`Ctrl + N` → **1080 × 1080 px**, 72 PPI, RGB, white", "Hold Space and drag to pan", "`Ctrl + 0` then `Ctrl + 1`: note the difference", "Save as **Lab01.psd**"],
        ["What's the difference between Ctrl + 0 and Ctrl + 1?", "Which Photoshop version are you using?"]),
      L("Layers Basics",
        "Layers are stacked sheets of glass. Edit one without touching the others. **Never flatten your work file.**",
        ["Top layer covers the ones below", "Eye icon hides/shows a layer", "Name layers: double-click the name", "Group related layers into folders"],
        [["Ctrl + Shift + N", "New layer"], ["Ctrl + J", "Duplicate layer / layer via copy"], ["Ctrl + G", "Group layers"], ["Ctrl + E", "Merge down"], ["Ctrl + ] / [", "Move layer up / down"]],
        "**Alt + click** an eye icon to solo that layer.",
        "Build a simple layered graphic.",
        ["Open Lab01.psd", "New layer → Rectangle (U) → fill blue", "New layer → Ellipse → fill yellow", "Name them **BG Box** and **Sun**", "Reorder so the sun is behind the box, then back on top", "Group both into a folder **Graphic**"],
        ["What happens when you reorder the layers?", "What does Ctrl + J do?"]),
      L("Move, Transform & Crop",
        "**Free Transform** scales, rotates and warps. **Crop** fixes composition and straightens horizons.",
        ["Ctrl + T, then drag handles; proportional by default in new versions", "Right-click inside transform for Warp, Flip, Perspective", "Crop tool has a **straighten** option in the Options bar", "Uncheck **Delete Cropped Pixels** to keep flexibility"],
        [["V", "Move tool"], ["Ctrl + T", "Free Transform"], ["C", "Crop tool"], ["Enter", "Commit transform/crop"], ["Esc", "Cancel"]],
        "Use **Smart Objects** (right-click layer → Convert to Smart Object) before scaling. You can resize again with no quality loss.",
        "Fix a crooked phone photo.",
        ["Open any photo from your phone", "`C` → use Straighten along the horizon", "Crop to 4:5 for Instagram", "Convert the layer to a Smart Object", "`Ctrl + T` → flip horizontal"],
        ["Screenshot before/after", "Did you keep Delete Cropped Pixels on or off?"])
    ]},
    { title: "Selections, Masks & Color", tag: "Building Blocks", lessons: [
      L("Selections",
        "A selection limits edits to one area. Modern tools make cutouts fast.",
        ["**Object Selection** / **Quick Selection** (W)", "**Select Subject** in the Options bar: one-click cutout", "**Select and Mask** refines hair and edges", "Add with Shift, subtract with Alt"],
        [["W", "Quick/Object selection"], ["M", "Marquee"], ["L", "Lasso"], ["Ctrl + D", "Deselect"], ["Ctrl + Shift + I", "Invert selection"]],
        "For hair, use **Select and Mask → Refine Hair** then output to a Layer Mask.",
        "Cut a person out for a flier.",
        ["Open a photo of a person", "Select → **Subject**", "Select and Mask → Refine edges", "Output to **New Layer with Layer Mask**", "Hide the original to check the cutout"],
        ["How clean was the hair edge?", "Which refine setting helped most?"]),
      L("Layer Masks",
        "Masks hide pixels without deleting them. **White reveals, black conceals.** Non-destructive editing.",
        ["Add mask: icon at bottom of Layers panel", "Paint black to hide, white to show", "Soft brush = smooth blends", "Alt + click mask thumbnail to view it"],
        [["B", "Brush"], ["D", "Default black/white"], ["X", "Swap colors"], ["[ / ]", "Brush size"], ["Shift + [ / ]", "Brush hardness"]],
        "Never use the eraser on client work. Masks let you undo anything, anytime.",
        "Blend two photos into one scene.",
        ["Place a sky photo above a city photo", "Add a layer mask to the sky", "Soft black brush → paint away the bottom of the sky", "Adjust with X to bring parts back"],
        ["Screenshot your blend", "Why is a mask better than the eraser?"]),
      L("Adjustment Layers & Color",
        "Adjustment layers change color and light without damaging pixels.",
        ["**Levels / Curves**: brightness and contrast", "**Hue/Saturation**: change colors", "**Color Balance**: warm or cool mood", "Clip an adjustment to one layer: Alt + click between layers"],
        [["Ctrl + L", "Levels (destructive)"], ["Ctrl + M", "Curves (destructive)"], ["Ctrl + U", "Hue/Saturation (destructive)"], ["Ctrl + Alt + G", "Create clipping mask"]],
        "Use the **Adjustments panel** versions, not Ctrl + L/M/U, on client work. They stay editable.",
        "Make a dull food photo look delicious.",
        ["Open a food photo", "Add a Curves adjustment → gentle S-curve", "Add Hue/Saturation → boost reds/yellows slightly", "Add Color Balance → warm the midtones", "Toggle all on/off to compare"],
        ["Which adjustment made the biggest difference?"])
    ]},
    { title: "Retouch, Type & Effects", tag: "Core Skills", lessons: [
      L("Retouching",
        "Clean skin, remove objects, fix distractions. The rule: **natural, not plastic**.",
        ["**Spot Healing** (J): blemishes and dust", "**Remove tool**: paint over objects to erase them", "**Clone Stamp** (S): copy exact texture", "Retouch on a **new empty layer** with Sample: All Layers"],
        [["J", "Healing tools"], ["S", "Clone stamp"], ["Alt + click", "Set clone source"], ["Ctrl + Shift + Alt + E", "Stamp visible layers"]],
        "Zoom to 100% for retouching, then zoom out often to check it still looks natural.",
        "Clean up a portrait for a CV photo.",
        ["Open a portrait", "New empty layer → Spot Healing with **Sample All Layers**", "Remove 5 blemishes or distractions", "Use the Remove tool to delete a background object"],
        ["Before/after screenshot", "Which tool did you use most?"]),
      L("Type & Layer Styles",
        "Photoshop type is great for social graphics. **Layer Styles** add stroke, shadow and glow.",
        ["Type tool (T): click for a line, drag for a box", "Double-click layer → Layer Style", "Stroke + Drop Shadow = readable text on any photo", "Save a style you like in the Styles panel"],
        [["T", "Type tool"], ["Ctrl + Shift + > / <", "Font size up/down"], ["Ctrl + Enter", "Commit text"], ["Alt + ← / →", "Tracking (kerning) while text selected"]],
        "For text on busy photos, add a **dark gradient** behind the text instead of heavy shadows.",
        "Headline for a crypto YouTube thumbnail.",
        ["New 1280 × 720 px doc", "Add a background photo", "Type **BITCOIN BREAKS OUT?** in heavy font", "Add a 6px stroke + subtle drop shadow", "Add a dark gradient layer behind the text"],
        ["Screenshot your thumbnail", "Which style settings did you use?"]),
      L("Blend Modes & Composites",
        "Blend modes mix layers mathematically. They create glow, light leaks and textures.",
        ["**Multiply**: darkens, removes white", "**Screen**: lightens, removes black", "**Overlay / Soft Light**: contrast and texture", "Great for adding light flares and grunge"],
        [["Shift + + / -", "Cycle blend modes (Move tool)"], ["Ctrl + Alt + G", "Clipping mask"], ["0-9", "Layer opacity (Move tool)"]],
        "Put a logo on black and set it to **Screen** to drop the black background instantly.",
        "Add dramatic light to a product shot.",
        ["Open a product photo", "Add a light flare / bokeh image on top", "Set blend mode to **Screen**", "Mask off where it's too strong", "Add a Soft Light texture layer at 30%"],
        ["Which blend modes did you try?"])
    ]},
    { title: "Social Graphic Project", tag: "Project", lessons: [
      L("Brief & Mood",
        "Every graphic answers a brief: audience, message, action. Collect a mood board first.",
        ["Audience: who scrolls past this?", "Message: one line", "Action: call, DM, visit, buy", "Mood board: 5 reference images"],
        [["Ctrl + N", "New document"], ["File → Place Embedded", "Place image"]],
        "Build mood boards on an artboard in Photoshop so references stay beside your work.",
        "Client: **Urban Kicks**, a sneaker store in Benin City. New drop this Friday.",
        ["Write audience / message / action", "Collect 5 reference sneaker ads", "Place them on a mood board canvas", "Pick 3 colors from them"],
        ["Share your brief and 3 colors"]),
      L("Product Composite",
        "Cut the product out, put it in a dramatic scene, match light and shadow.",
        ["Cutout with Select Subject + mask", "Add a **contact shadow** under the product", "Match color with Color Balance clipped to the product", "Add rim light with a Screen layer"],
        [["Ctrl + J", "Layer via copy"], ["Ctrl + T", "Transform"], ["Ctrl + Alt + G", "Clip adjustment"]],
        "Contact shadow: new layer under product, soft black brush, low opacity, squash with Ctrl + T.",
        "Build the sneaker hero image.",
        ["Cut out a sneaker photo", "Place it on a gradient or street background", "Add a contact shadow", "Color match with clipped adjustments", "Add a glow or light streak"],
        ["Screenshot your composite", "How did you make the shadow?"]),
      L("Type, Offer & Export",
        "Add headline, price/offer and CTA. Export sharp for Instagram.",
        ["Headline big, CTA short (DM TO ORDER)", "Brand logo in a corner", "Export: File → Export → **Export As** → JPG", "Check it on your phone"],
        [["Alt + Shift + Ctrl + W", "Export As"], ["Ctrl + Shift + S", "Save As"]],
        "Look at it on your actual phone at arm's length before sending to a client.",
        "Finish and export the Urban Kicks post.",
        ["Add headline, date, price and CTA", "Add logo", "Export 1080 × 1350 JPG", "Send it to your phone and review"],
        ["Final screenshot", "What did you change after viewing on phone?"])
    ]},
    { title: "Flier Project", tag: "Project", lessons: [
      L("Print Flier Setup",
        "Photoshop fliers need **300 PPI, CMYK and bleed**.",
        ["A5 + 3 mm bleed = **154 × 216 mm**", "Guides at 3 mm (trim) and 8 mm (safe)", "Use View → **New Guide Layout**", "Keep text inside the safe zone"],
        [["Ctrl + R", "Rulers"], ["Ctrl + ;", "Show/hide guides"], ["Ctrl + '", "Show grid"]],
        "Design in RGB with Smart Objects, then convert a **copy** to CMYK at the end to keep colors editable.",
        "Flier: **Sunday Praise Night**, church youth event.",
        ["New doc 154 × 216 mm, 300 PPI", "Add trim and safe guides", "Rough in headline, photo, details, CTA zones"],
        ["Describe your layout zones"]),
      L("Design the Flier",
        "Use a strong photo, overlay, bold type and clean info blocks.",
        ["Hero photo + gradient overlay", "Headline with layer style", "Info in a clean box: date · time · venue", "Logos of organizers at the bottom"],
        [["G", "Gradient tool"], ["U", "Shape tools"], ["T", "Type"]],
        "Use a **Gradient Map** adjustment for instant, on-brand color grading.",
        "Build the Praise Night flier.",
        ["Place the hero photo", "Add a Gradient Map in brand colors", "Add headline and info block", "Add logos and contact"],
        ["Screenshot", "Which gradient colors did you use?"]),
      L("Proof & Print PDF",
        "Check text, resolution and color, then export a PDF for the printer.",
        ["View → Proof Colors (Ctrl + Y) to preview CMYK", "Fix colors that go dull", "Save a copy as **Photoshop PDF**, High Quality Print", "Keep the layered PSD master"],
        [["Ctrl + Y", "Proof colors"], ["Ctrl + Shift + S", "Save As (PDF)"]],
        "Bright RGB greens and blues die in CMYK. Check them in Proof Colors early.",
        "Prepare the flier for print.",
        ["Toggle Proof Colors and fix dull areas", "Proofread all text", "Save **Flier_MASTER.psd**", "Save a copy as PDF (High Quality Print)"],
        ["Which colors changed most in proof?"])
    ]},
    { title: "Poster Project", tag: "Project", lessons: [
      L("Cinematic Poster Concept",
        "Movie-style posters sell events and products. Big subject, dramatic light, minimal type.",
        ["Pick a **hero**: person or object", "Create depth: background, midground, foreground", "Lighting tells the mood", "Title at bottom or top third"],
        [["Ctrl + N", "New"], ["Ctrl + J", "Duplicate"]],
        "Study 3 movie posters. Note where the title sits and how light falls on the hero.",
        "Poster for a Nollywood-style short film **\"The Last Harvest\"**.",
        ["A3 size, 300 PPI", "Collect a hero portrait + background", "Sketch placement: hero, title, credits"],
        ["Describe your concept"]),
      L("Build the Composite",
        "Layer hero, background, atmosphere and light effects.",
        ["Cut out the hero", "Add fog/smoke with Screen blend", "Color grade everything with one Gradient Map + Curves", "Add vignette for focus"],
        [["W", "Selection"], ["B", "Brush"], ["Ctrl + Alt + G", "Clip"]],
        "One global color grade on top unifies photos from different sources.",
        "Build the poster composite.",
        ["Background, hero, atmosphere layers", "Global color grade", "Vignette", "Rim light on the hero"],
        ["Screenshot"]),
      L("Title & Credits",
        "Poster typography: bold title, tight credits block, release date.",
        ["Title with texture or subtle bevel", "Credits block in condensed font", "Date in accent color", "Export JPG + print PDF"],
        [["T", "Type"], ["Alt + Shift + Ctrl + W", "Export As"]],
        "Credits blocks use a **condensed** font with tight leading. That's the classic look.",
        "Finish \"The Last Harvest\" poster.",
        ["Add title with texture", "Credits block", "Date + tagline", "Export JPG and PDF"],
        ["Final screenshot"])
    ]},
    { title: "Export, Actions & Portfolio", tag: "Pro", lessons: [
      L("Export for Web & Print",
        "Right format, right size, right color every time.",
        ["JPG: photos · PNG: transparency · PDF: print", "Export As lets you set exact pixel size", "sRGB for web", "Keep files under 1 MB for WhatsApp/Instagram"],
        [["Alt + Shift + Ctrl + W", "Export As"], ["Ctrl + Shift + S", "Save As"]],
        "**Quick Export as PNG** (File → Export) saves settings for fast repeat exports.",
        "Export all your projects correctly.",
        ["Export the sneaker post as JPG", "Export a logo as transparent PNG", "Export the flier as PDF", "Compare file sizes"],
        ["List files and sizes"]),
      L("Actions & Batch",
        "Actions record steps and replay them. Batch applies them to 100 photos in seconds.",
        ["Window → Actions → New Action → Record", "Stop when done", "File → Automate → Batch", "Great for watermarking and resizing"],
        [["Alt + F9", "Actions panel"]],
        "Build a **watermark action** for client previews so work can't be stolen before payment.",
        "Batch-resize 5 photos.",
        ["Record an action: resize to 1080 px wide + save JPG", "Put 5 photos in a folder", "Run Batch on the folder"],
        ["Did the batch work?"]),
      L("Portfolio",
        "Show before/after and process. That's what wins retouching and design clients.",
        ["3 projects: social post, flier, poster", "Before/after sliders for retouch", "Mockups for context", "Short captions: problem → solution"],
        [["Ctrl + N", "New"], ["Alt + Shift + Ctrl + W", "Export As"]],
        "Use a free **phone/poster mockup PSD** and drop your design into its Smart Object.",
        "Build a portfolio post.",
        ["Make a 1080 × 1350 carousel: cover + 3 projects", "Add captions", "Export all slides"],
        ["Share your cover caption"])
    ]}
  ]
});
