UDL_TRACKS.push({
  id: "powerpoint", num: 7, name: "PowerPoint", abbr: "P", color: "#FF6A3D", group: "office",
  focus: "Pitch Decks · Presentations · Promo Graphics",
  intro: "Decks that win pitches. Plus a secret: PowerPoint is a fast design tool for fliers, posters and promo videos.",
  modules: [
    { title: "Interface & Core Tools", tag: "Foundations", lessons: [
      L("Slides, Layouts & Views",
        "Slides use **layouts** with placeholders. Normal view for editing, Slide Sorter for structure.",
        ["Home → Layout changes a slide's structure", "Thumbnails panel (left) reorders slides", "Slide Sorter view for the big picture", "Design → Slide Size: 16:9 default"],
        [["Ctrl + M", "New slide"], ["Ctrl + D", "Duplicate selected"], ["F5", "Present from start"], ["Shift + F5", "Present from current"], ["Ctrl + S", "Save"]],
        "**Duplicate** your best slide (Ctrl + D) instead of starting fresh. Consistency for free.",
        "Start a pitch deck.",
        ["New blank presentation", "Slide 1: Title layout → **Urban Digital Learning**", "`Ctrl + M` → add 4 slides with different layouts", "Reorder in Slide Sorter", "Press `F5` to preview"],
        ["What layouts did you use?", "PowerPoint version?"]),
      L("Text & Alignment",
        "Clean slides = few words, big type, perfect alignment.",
        ["Max **6 words per line**, 6 lines per slide", "Title 36-44pt, body 20-28pt", "Smart Guides snap objects", "Arrange → Align for precision"],
        [["Ctrl + Shift + > / <", "Font size"], ["Ctrl + E / L / R", "Align text"], ["Shift + drag", "Straight move / proportional resize"], ["Ctrl + drag", "Duplicate object"]],
        "If a slide needs a paragraph, it's a **document**, not a slide.",
        "Rewrite a wordy slide.",
        ["Paste a paragraph onto a slide", "Cut it to 3 bullets of ≤6 words", "Increase size to 28pt", "Align the text box to the slide's left margin"],
        ["Before/after word count?"]),
      L("Shapes, Images & Grouping",
        "Shapes and images build visual slides. Group to move as one.",
        ["Insert → Shapes, Pictures, Icons", "Crop images to shapes", "Format Painter copies styles", "Selection Pane names and hides objects"],
        [["Ctrl + G", "Group"], ["Ctrl + Shift + G", "Ungroup"], ["Ctrl + Shift + C / V", "Copy / paste formatting"], ["Alt + F10", "Selection Pane"]],
        "**Crop to Shape → Circle** for team photos in 2 clicks.",
        "Build a team slide.",
        ["Insert 3 photos", "Crop each to a circle, same size", "Name + role below each", "Group each person and distribute evenly"],
        ["Screenshot"])
    ]},
    { title: "Design, Masters & Color", tag: "Building Blocks", lessons: [
      L("Slide Master",
        "The **Slide Master** controls fonts, colors and logos on every slide.",
        ["View → Slide Master", "Edit the top master for global changes", "Edit layouts for specific slide types", "Add logo once, appears everywhere"],
        [["Shift + click Normal view icon", "Open Slide Master"]],
        "Build your master **first**. Changing 40 slides by hand later is pain.",
        "Brand your deck.",
        ["Open Slide Master", "Set theme fonts and colors", "Add logo bottom-right", "Close master and check slides"],
        ["Screenshot"]),
      L("Color & Themes",
        "Design → Variants → Colors → **Customize Colors** sets your brand palette.",
        ["2 main colors + 1 accent", "Dark text on light or light on dark", "Keep contrast high for projectors", "Save as a theme (.thmx)"],
        [["Eyedropper in color menu", "Match any color"]],
        "Projectors wash out colors. Test with **high contrast**.",
        "Create a brand theme.",
        ["Custom theme colors", "Theme fonts", "Save current theme"],
        ["Your colors"]),
      L("Designer & Layout Rules",
        "Designer suggests layouts; the rules make them great.",
        ["Design → Designer for ideas", "Rule of thirds", "Whitespace is not wasted", "One idea per slide"],
        [["Design → Designer", "Design ideas"], ["Ctrl + D", "Duplicate slide"]],
        "Use Designer for **ideas**, then refine by hand.",
        "Redesign 3 slides.",
        ["Try Designer on 3 slides", "Pick and refine", "Apply rule of thirds on one"],
        ["Screenshot before/after"])
    ]},
    { title: "Animation, Charts & Media", tag: "Core Skills", lessons: [
      L("Animations & Morph",
        "Subtle animation guides attention. **Morph** makes cinematic transitions.",
        ["Entrance: Fade, Wipe (subtle is pro)", "Animation Pane for order and timing", "Morph: duplicate a slide, move objects", "Avoid spins and bounces"],
        [["Alt + A", "Animations tab"], ["Ctrl + D", "Duplicate slide"]],
        "Morph = duplicate slide + move/resize objects + Transitions → **Morph**.",
        "Create a Morph effect.",
        ["Slide with a big logo center", "Duplicate", "Move logo small top-left, add text", "Apply Morph to slide 2", "Play"],
        ["Did it animate smoothly?"]),
      L("Charts & SmartArt",
        "Show data visually and processes clearly.",
        ["Insert → Chart (edits in Excel)", "SmartArt for processes and cycles", "Simplify: remove gridlines", "Highlight the key bar in accent color"],
        [["Insert → Chart", "New chart"], ["Ctrl + G", "Group"]],
        "Color **one bar** in the accent color; grey the rest. The audience sees your point instantly.",
        "Market size slide.",
        ["Insert a column chart", "Enter 4 data points", "Highlight one bar", "Add a one-line takeaway title"],
        ["Screenshot"]),
      L("Video & Audio",
        "Embed videos and music; trim inside PowerPoint.",
        ["Insert → Video → This Device", "Playback → Trim", "Start: Automatically", "Compress media for sharing"],
        [["Alt + P", "Play / pause selected video"], ["Alt + End", "Next bookmark"]],
        "File → Info → **Compress Media** before emailing a heavy deck.",
        "Add a video to a slide.",
        ["Insert a short clip", "Trim to 10 s", "Autoplay", "Compress media"],
        ["Final file size?"])
    ]},
    { title: "Pitch Deck Project", tag: "Project", lessons: [
      L("Pitch Story",
        "Investors follow a story: problem → solution → market → traction → ask.",
        ["10 slides max", "Problem, Solution, Product, Market, Business Model", "Traction, Team, Competition, Financials, Ask", "One message per slide"],
        [["Ctrl + M", "New slide"]],
        "Write **slide titles as sentences**: \"Nigerians waste 3 hours a week...\". Read titles only: that's your story.",
        "Pitch for **Shardplay**.",
        ["Write 10 slide titles as sentences", "Add rough content"],
        ["Share your 10 titles"]),
      L("Design the Deck",
        "Apply master, visuals, charts and icons.",
        ["Big visuals, few words", "Consistent icons", "Charts for traction", "Team photos"],
        [["Ctrl + G", "Group"], ["Alt + F10", "Selection Pane"]],
        "Every slide should pass the **3-second test**: what's the point?",
        "Design all 10 slides.",
        ["Apply master", "Visuals and icons", "Chart and team slides"],
        ["Screenshot 3 slides"]),
      L("Rehearse & Present",
        "Presenter view, notes, timing.",
        ["Speaker notes under each slide", "Presenter View shows notes + next slide", "Rehearse Timings", "B = black screen, W = white"],
        [["Alt + F5", "Presenter View"], ["B / W", "Black / white screen"], ["Number + Enter", "Jump to slide"]],
        "Type a slide number + **Enter** during a show to jump there when questions come.",
        "Rehearse your pitch.",
        ["Add notes", "Rehearse Timings", "Aim for 5 minutes"],
        ["Your total time?"])
    ]},
    { title: "Flier & Poster in PowerPoint", tag: "Project", lessons: [
      L("Custom Slide Sizes",
        "PowerPoint is a secret design tool. Set slide size to A4, A3 or 1080 px square.",
        ["Design → Slide Size → Custom", "A4 = 21 × 29.7 cm", "Square: 1080 × 1080 px ≈ 28.57 cm", "Portrait for fliers"],
        [["Design → Slide Size", "Custom size"], ["Alt + F9", "Show/hide guides"]],
        "Many Nigerian church and event fliers are made in PowerPoint. Do it **better** with grids and hierarchy.",
        "Set up a flier.",
        ["Custom A5 portrait slide", "Add guides: right-click → Grid and Guides", "Block layout"],
        ["Layout description"]),
      L("Design the Flier",
        "Background, image, headline, details, CTA.",
        ["Full-bleed background", "Photo with gradient overlay shape", "Bold headline", "Details and logos"],
        [["Ctrl + G", "Group"], ["Ctrl + Shift + C / V", "Format painter"]],
        "Make a transparent gradient overlay: shape → Gradient fill with **transparency 0% to 100%**.",
        "Flier: **Chainsense Crypto Meetup**.",
        ["Background + photo", "Gradient overlay", "Headline and details", "QR code placeholder"],
        ["Screenshot"]),
      L("Export Image & PDF",
        "Export slides as high-res PNG and PDF.",
        ["File → Export → PDF", "Save As → PNG", "High-res: File → Options → Advanced → Image size", "Check on phone"],
        [["F12", "Save As"]],
        "Set export resolution to **300 PPI** in Options for crisp print images.",
        "Export the flier.",
        ["Export PNG", "Export PDF", "Send to phone and check"],
        ["File sizes?"])
    ]},
    { title: "Promo Video Project", tag: "Project", lessons: [
      L("Animated Poster",
        "Animate a poster design for Instagram and WhatsApp status.",
        ["9:16 slide: 1080 × 1920 px", "Stagger entrance animations", "Morph between 3 slides", "Timing 0.5-1 s per element"],
        [["Alt + A", "Animations"], ["F5", "Preview"]],
        "Use **After Previous** with small delays for smooth auto sequences.",
        "Animated promo poster.",
        ["Vertical slide", "Headline, image, details", "Staggered animations", "Preview"],
        ["Did the timing feel smooth?"]),
      L("Music & Timing",
        "Add background music across slides and auto-advance.",
        ["Insert → Audio", "Play Across Slides", "Transitions: After X seconds", "Hide audio icon during show"],
        [["Alt + K", "Transitions tab"]],
        "Match slide changes to the music's **beat**. Viewers feel it.",
        "Add music and timing.",
        ["Insert audio across slides", "Auto-advance slides", "Preview the whole thing"],
        ["Total length?"]),
      L("Export Video",
        "Export MP4 for socials straight from PowerPoint.",
        ["File → Export → Create a Video", "Full HD 1080p", "Use recorded timings", "Check on phone"],
        [["F12", "Save As"]],
        "Export at **Full HD**. 4K bloats file size for no gain on phones.",
        "Export your promo.",
        ["Create video 1080p", "Play on phone", "Share to status"],
        ["Screenshot of final video frame"])
    ]},
    { title: "Pro Workflow & Portfolio", tag: "Pro", lessons: [
      L("Templates",
        "Save your master as a template (.potx) for fast branded decks.",
        ["Clean master", "Placeholder layouts", "Save as .potx", "Share with team"],
        [["F12", "Save As"]],
        "Sell deck templates to businesses and churches. **Reusable = scalable**.",
        "Create a deck template.",
        ["Clean master with 5 layouts", "Save as .potx", "New deck from it"],
        ["Screenshot"]),
      L("Accessibility & Handoff",
        "Readable slides and clean files.",
        ["Check Accessibility (Review tab)", "Alt text for images", "Embed fonts on save", "PDF handout version"],
        [["Review → Check Accessibility", "Accessibility checker"], ["F12", "Save As"]],
        "Embed fonts (File → Options → Save) so the deck looks right on **any** computer.",
        "Prepare your deck for sharing.",
        ["Run accessibility check", "Embed fonts", "Export PDF handout"],
        ["Any issues found?"]),
      L("Portfolio",
        "Show decks, fliers and promo videos.",
        ["Best 5 slides from pitch", "Flier and promo video", "Short case study", "Post online"],
        [["F5", "Present"]],
        "Record a **30-second screen video** flipping through your deck for social media.",
        "Build your PowerPoint portfolio.",
        ["Showcase deck", "Export PDF + video"],
        ["Share your caption"])
    ]}
  ]
});
