UDL_TRACKS.push({
  id: "premiere", num: 8, name: "Premiere Pro", abbr: "Pr", color: "#B784FF", group: "video",
  focus: "Pro Editing · Color · Audio · YouTube",
  intro: "The editor behind YouTube channels, ads and films. Cut, grade, mix and export like a studio.",
  modules: [
    { title: "Interface & Core Tools", tag: "Foundations", lessons: [
      L("Projects, Panels & Media",
        "Premiere is **non-destructive**: your footage is never changed; the project just points to it.",
        ["**Project panel**: your imported media", "**Source monitor**: preview clips", "**Program monitor**: your edit", "**Timeline**: where you build the story"],
        [["Ctrl + Alt + N", "New project"], ["Ctrl + I", "Import"], ["Space", "Play / stop"], ["` (grave)", "Maximize panel"], ["Ctrl + S", "Save"]],
        "Organize media into **bins** (folders) from day one: Footage, Audio, Graphics, Music.",
        "Set up a YouTube project.",
        ["New project **Chainsense_Ep01**", "Import 3-5 video clips and 1 music track", "Create bins: Footage, Audio", "Drag clips into bins", "Double-click a clip to preview in Source"],
        ["How many clips imported?", "Premiere Pro version?"]),
      L("Sequences & The Timeline",
        "A **sequence** is your edit. Its settings (resolution, frame rate) should match your footage.",
        ["Drag a clip onto the New Item icon = matched sequence", "V1, V2 = video tracks (top covers bottom)", "A1, A2 = audio tracks", "Playhead shows current frame"],
        [["Ctrl + N", "New sequence"], ["+ / -", "Zoom timeline"], ["\\", "Fit sequence in timeline"], ["↑ / ↓", "Jump between edits"]],
        "Always create sequences from a clip to avoid **resolution mismatches**.",
        "Build your first sequence.",
        ["Drag your main clip onto the New Item icon", "Rename sequence **Ep01_Edit**", "Zoom with + and -", "Press \\ to fit"],
        ["What resolution and frame rate did it pick?"]),
      L("J-K-L & Marking",
        "Pros never drag clips blindly. **Mark In/Out** then insert.",
        ["J = reverse, K = pause, L = forward (tap L twice = 2×)", "I = mark In, O = mark Out", "Comma = insert, Period = overwrite", "Mark only the good part of each clip"],
        [["J / K / L", "Shuttle play"], ["I / O", "Mark In / Out"], [",", "Insert"], [".", "Overwrite"], ["M", "Add marker"]],
        "Hold **K + tap J or L** to move one frame at a time.",
        "Assemble a rough cut.",
        ["Open a clip in Source", "Mark In/Out on the best 5 seconds", "Press , to insert into timeline", "Repeat for 4 more clips"],
        ["Rough cut length?"])
    ]},
    { title: "Editing Tools", tag: "Building Blocks", lessons: [
      L("Cut & Trim",
        "Trimming shapes pacing. Tight edits keep viewers watching.",
        ["Razor (C) cuts clips", "Ripple Delete removes gap", "Q / W ripple trims to playhead", "Selection (V) trims edges"],
        [["C", "Razor"], ["Ctrl + K", "Add edit at playhead"], ["Q / W", "Ripple trim previous / next"], ["Shift + Delete", "Ripple delete"], ["V", "Selection tool"]],
        "Edit talking-head videos with **Q and W** only. Fastest way to cut ums and pauses.",
        "Tighten a talking clip.",
        ["Record a 1-minute talking clip", "Cut every pause with Ctrl + K + Q/W", "Ripple delete gaps", "Compare length before/after"],
        ["Before/after length?"]),
      L("B-Roll & Layers",
        "B-roll covers cuts and shows what you're talking about.",
        ["Main talk on V1, B-roll on V2", "Audio stays from V1", "Scale B-roll in Effect Controls", "Link/unlink audio: select and Ctrl + L"],
        [["Ctrl + L", "Link / unlink"], ["Alt + drag", "Duplicate clip"], ["Shift + 5", "Effect Controls panel"]],
        "Cut B-roll **on action** (movement) so transitions feel natural.",
        "Add B-roll.",
        ["Place 3 B-roll clips on V2", "Mute their audio", "Scale to fill frame"],
        ["Screenshot of timeline"]),
      L("Transitions & Speed",
        "Most cuts should be **hard cuts**. Use transitions sparingly.",
        ["Cross Dissolve for time passing", "Dip to Black for endings", "Speed/Duration for slow-mo", "Rate Stretch (R) to fit time"],
        [["Ctrl + D", "Default video transition"], ["Ctrl + Shift + D", "Default audio transition"], ["Ctrl + R", "Speed/Duration"], ["R", "Rate stretch"]],
        "Add a 2-frame **audio crossfade** (Ctrl + Shift + D) at every cut to kill clicks.",
        "Add transitions and speed ramp.",
        ["Dissolve between two scenes", "Slow one clip to 50%", "Audio crossfades on all cuts"],
        ["Which effect looked best?"])
    ]},
    { title: "Text, Audio & Color", tag: "Core Skills", lessons: [
      L("Titles & Graphics",
        "Essential Graphics panel creates titles, lower thirds and templates.",
        ["Type tool (T) in Program monitor", "Essential Graphics: styles, shapes", "Responsive design pins elements", "Save as Motion Graphics Template"],
        [["T", "Type tool"], ["Shift + 7", "Effects panel"]],
        "Build a **lower-third template** once; reuse it in every episode.",
        "Create a lower third.",
        ["Add name + title text", "Background shape", "Simple slide-in animation", "Save as .mogrt"],
        ["Screenshot"]),
      L("Audio Mixing",
        "Bad audio kills videos faster than bad video.",
        ["Essential Sound: tag Dialogue, Music, SFX", "Dialogue: -6 to -3 dB peaks", "Music under voice: ~-20 dB", "Auto Ducking lowers music under talk"],
        [["Alt + drag", "Keyframe audio"], ["Shift + 6", "Audio Track Mixer"]],
        "Use **Enhance Speech** (Essential Sound) to clean phone-recorded voice.",
        "Mix your episode.",
        ["Tag clips in Essential Sound", "Enhance speech", "Add music and auto-duck", "Check peaks"],
        ["Peak level achieved?"]),
      L("Color Correction & Grading",
        "Correct first (fix), then grade (style). Lumetri Color does both.",
        ["Basic: exposure, white balance, contrast", "Use scopes (Lumetri Scopes)", "Creative: LUTs and looks", "Adjustment layer grades everything"],
        [["Window → Lumetri Color", "Color panel"]],
        "Grade on an **adjustment layer** over the whole timeline for consistent style.",
        "Color the episode.",
        ["Correct white balance and exposure", "Add adjustment layer", "Apply a creative look at 50%"],
        ["Before/after screenshot"])
    ]},
    { title: "YouTube Video Project", tag: "Project", lessons: [
      L("Plan & Script",
        "Great videos start with a hook in the first **5 seconds**.",
        ["Hook: question or bold claim", "Structure: hook → value → CTA", "Shot list", "B-roll list"],
        [["M", "Marker for key moments"]],
        "Script the **first 15 seconds** word-for-word. That decides retention.",
        "Plan a Chainsense crypto update video.",
        ["Write a 5-second hook", "Outline 3 segments", "List B-roll needed"],
        ["Your hook"]),
      L("Edit the Episode",
        "Assemble, tighten, layer B-roll and graphics.",
        ["Talking head tight cuts", "Zoom-ins (scale 110%) for emphasis", "B-roll + lower thirds", "Captions"],
        [["Q / W", "Ripple trim"], ["Ctrl + K", "Add edit"]],
        "Punch-in zooms between cuts hide jump cuts on single-camera shoots.",
        "Edit a 3-minute episode.",
        ["Assemble and tighten", "Punch-ins", "B-roll, lower third", "Auto captions (Text panel → Transcribe)"],
        ["Final length?"]),
      L("Thumbnail Frame & Export",
        "Export YouTube-ready and pull a thumbnail frame.",
        ["Export: File → Export → Media", "H.264, Match Source - High", "Export Frame for thumbnail", "Check audio on phone"],
        [["Ctrl + M", "Export media"], ["Ctrl + Shift + E", "Export frame"]],
        "Use the **YouTube 1080p** preset for fast, compliant uploads.",
        "Export the episode.",
        ["Export H.264 1080p", "Export a thumbnail frame", "Watch on phone"],
        ["File size?"])
    ]},
    { title: "Promo Ad Project", tag: "Project", lessons: [
      L("30-Second Ad Structure",
        "Ads: hook, problem, solution, offer, CTA in **30 seconds**.",
        ["0-3 s hook", "3-15 s problem/solution", "15-25 s offer", "25-30 s CTA + logo"],
        [["M", "Markers for beats"]],
        "Place **markers on music beats** (tap M while playing) and cut to them.",
        "Ad for **Urban Kicks** sneaker drop.",
        ["Choose music", "Mark beats", "Plan shots for each beat"],
        ["Your ad outline"]),
      L("Edit to the Beat",
        "Cut on beats, animate text, keep energy up.",
        ["Cuts on markers", "Text animations with keyframes", "Speed ramps", "Sound effects (whoosh)"],
        [["Shift + M", "Next marker"], ["Ctrl + Shift + M", "Previous marker"]],
        "Enable **snapping (S)** so cuts lock exactly to markers.",
        "Edit the ad.",
        ["Cut to beats", "Animated text", "Speed ramp", "SFX"],
        ["Screenshot of timeline"]),
      L("Multi-Format Export",
        "One ad, three formats: 16:9, 1:1, 9:16.",
        ["Duplicate sequence", "Auto Reframe for vertical", "Adjust text positions", "Export all"],
        [["Ctrl + M", "Export"]],
        "**Auto Reframe** tracks the subject when converting to vertical.",
        "Export 3 versions.",
        ["Duplicate for 1:1 and 9:16", "Auto Reframe", "Fix text", "Export all"],
        ["Which format looked best?"])
    ]},
    { title: "Logo Sting & Poster Motion", tag: "Project", lessons: [
      L("Animated Logo Intro",
        "A 3-second logo sting brands every video.",
        ["Import logo PNG/AI", "Scale + opacity keyframes", "Add a whoosh SFX", "Export for reuse"],
        [["Toggle stopwatch", "Start keyframing"]],
        "Use **Ease In/Out** (right-click keyframe) for smooth, pro motion.",
        "Build a Chainsense logo sting.",
        ["Logo on black", "Scale 80→100% with ease", "Glow or light sweep", "SFX + export"],
        ["Screenshot"]),
      L("Motion Poster",
        "Animate a still poster: parallax layers and text reveals.",
        ["Import layered PSD as sequence", "Move layers at different speeds", "Text reveal with masks", "Loop-friendly 10 s"],
        [["Ctrl + I", "Import PSD"]],
        "Import PSD as **Sequence** to get each layer separately.",
        "Animate your poster.",
        ["Import poster PSD layers", "Parallax move", "Text reveal", "Export 10 s MP4"],
        ["Result length?"]),
      L("Social Captions",
        "Most social video is watched muted. Captions are mandatory.",
        ["Text panel → Transcribe", "Create captions", "Style: big, bold, centered", "Burn-in on export"],
        [["Window → Text", "Captions panel"]],
        "Keep captions to **2 lines max** and 32 characters per line.",
        "Caption a short clip.",
        ["Transcribe", "Create and style captions", "Export with burn-in"],
        ["Any transcription errors?"])
    ]},
    { title: "Pro Workflow & Portfolio", tag: "Pro", lessons: [
      L("Proxies & Performance",
        "Edit 4K smoothly on modest laptops with proxies.",
        ["Ingest settings → Create proxies", "Toggle proxy button", "Lower playback resolution (1/2, 1/4)", "Clear media cache"],
        [["Button Editor (+) → Toggle Proxies", "Add proxy button"]],
        "Set playback resolution to **1/2** while editing; full only for final checks.",
        "Optimize your project.",
        ["Create proxies for 2 clips", "Toggle proxies", "Change playback res"],
        ["Did playback improve?"]),
      L("Project Management",
        "Archive projects cleanly for clients and backups.",
        ["File → Project Manager", "Consolidate and transcode", "Collect files and copy", "Name versions: v01, v02"],
        [["Ctrl + S", "Save"]],
        "Never overwrite: save **v01, v02...** so you can go back.",
        "Archive your YouTube project.",
        ["Run Project Manager", "Copy to new folder", "Open the copy to verify"],
        ["Archive size?"]),
      L("Showreel",
        "A 60-second showreel of your best shots wins editing gigs.",
        ["Best 10-15 moments", "Fast pace, music-driven", "Name + contact at end", "Upload to YouTube/Vimeo"],
        [["M", "Markers"], ["Ctrl + M", "Export"]],
        "Open with your **single best shot**. First 5 seconds decide.",
        "Cut your showreel.",
        ["Select best moments", "Cut to music", "End card", "Export"],
        ["Showreel length?"])
    ]}
  ]
});
